backend:
  name: github
  repo: art-vision-studio/dasha-risunki
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Галерея"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Картинка", name: "image", widget: "image" }
      - { label: "Описание", name: "description", widget: "text", required: false }
